src/DeepSpaceOne/GameBundle/Entity/Ship.php
<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace DeepSpaceOne\GameBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * A space ship.
 *
 * @Entity
 *
 * @author Bernhard Schussek <bschussek@gmail.com>
 */
class Ship
{
    /**
     * @Id
     * @GeneratedValue
     * @Column(type="integer")
     *
     * @var integer
     */
    private $id;

    /**
     * The ship's name.
     *
     * @Column(type="string", nullable=false)
     *
     * @Assert\NotNull
     * @Assert\Length(min=3)
     *
     * @var string
     */
    private $name;

    /**
     * The type of the ship.
     *
     * @ManyToOne(targetEntity="ShipClass")
     *
     * @Assert\NotNull
     *
     * @var ShipClass
     */
    private $class;

    /**
     * The payload the ship is carrying.
     *
     * @OneToMany(targetEntity="Payload", mappedBy="ship", cascade={"persist", "remove"})
     *
     * @Assert\NotNull
     * @Assert\Valid
     *
     * @var \Doctrine\Common\Collections\Collection<Payload>
     */
    private $payload;

    /**
     * The mountPoints for mounting equipment.
     *
     * @OneToMany(targetEntity="MountPoint", mappedBy="ship", cascade={"persist", "remove"})
     *
     * @Assert\NotNull
     * @Assert\Valid
     *
     * @var \Doctrine\Common\Collections\Collection<MountPoint>
     */
    private $mountPoints;

    public function __construct(ShipClass $class = null)
    {
        $this->class = $class;

        $this->clearPayload();
        $this->clearMountPoints();
    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param ShipClass $class
     */
    public function setClass(ShipClass $class)
    {
        $this->class = $class;
    }

    /**
     * @return ShipClass
     */
    public function getClass()
    {
        return $this->class;
    }

    /**
     * @return MountPoint[]
     */
    public function getMountPoints()
    {
        return $this->mountPoints->toArray();
    }

    /**
     * @param MountPoint $mountPoint
     */
    public function addMountPoint(MountPoint $mountPoint)
    {
        $this->mountPoints[] = $mountPoint;

        $mountPoint->setShip($this);
    }

    /**
     * @param MountPoint $mountPoint
     */
    public function removeMountPoint(MountPoint $mountPoint)
    {
        $this->mountPoints->removeElement($mountPoint);

        if ($this === $mountPoint->getShip()) {
            $mountPoint->setShip(null);
        }
    }

    /**
     * Clears the mount points.
     */
    public function clearMountPoints()
    {
        $this->mountPoints = new ArrayCollection();
    }

    /**
     * @return integer
     */
    public function getEquipmentCapacity()
    {
        return $this->class ? $this->class->getEquipmentCapacity() : 0;
    }

    /**
     * @return \SplObjectStorage
     */
    public function getEquipmentSummary()
    {
        $summary = new \SplObjectStorage();

        foreach ($this->mountPoints as $mountPoint) {
            if (null !== $mountPoint->getEquipment()) {
                if (!isset($summary[$mountPoint->getEquipment()])) {
                    $summary[$mountPoint->getEquipment()] = 0;
                }

                $summary[$mountPoint->getEquipment()] += 1;
            }
        }

        return $summary;
    }

    /**
     * @return Payload[]
     */
    public function getPayload()
    {
        return $this->payload->toArray();
    }

    /**
     * @return \SplObjectStorage
     */
    public function getPayloadSummary()
    {
        $summary = new \SplObjectStorage();

        foreach ($this->payload as $payload) {
            if (null !== $payload->getGood() && !isset($summary[$payload->getGood()])) {
                $summary[$payload->getGood()] = 0;
            }

            $summary[$payload->getGood()] += $payload->getMass();
        }

        return $summary;
    }

    /**
     * @return integer
     */
    public function getPayloadCapacity()
    {
        return $this->class ? $this->class->getPayloadCapacity() : 0;
    }

    public function getPayloadMass()
    {
        $mass = 0;

        foreach ($this->payload as $payload) {
            $mass += $payload->getMass();
        }

        return $mass;
    }

    /**
     * @param Payload $payload
     */
    public function addPayload(Payload $payload)
    {
        $this->payload[] = $payload;

        $payload->setShip($this);
    }

    /**
     * @param Payload $payload
     */
    public function removePayload(Payload $payload)
    {
        $this->payload->removeElement($payload);

        if ($this === $payload->getShip()) {
            $payload->setShip(null);
        }
    }

    /**
     * Clears the payload.
     */
    public function clearPayload()
    {
        $this->payload = new ArrayCollection();
    }
}

src/DeepSpaceOne/GameBundle/Controller/ShipClassController.php
<?php

namespace DeepSpaceOne\GameBundle\Controller;

use DeepSpaceOne\GameBundle\Entity\ShipClass;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * Handles the ship class CRUD operations.
 *
 * @Route("/classes")
 *
 * @author Bernhard Schussek <bschussek@gmail.com>
 */
class ShipClassController extends Controller
{
    /**
     * Lists all ShipClass entities.
     *
     * @Route("/", name="classes")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $classes = $em->getRepository('DeepSpaceOneGameBundle:ShipClass')->findAll();

        return array(
            'classes' => $classes,
        );
    }

    /**
     * Displays a form to create a new ShipClass entity.
     *
     * @Route("/new", name="classes_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        // TASK 2: create form

        return array(
            // TASK 2: pass form to view
        );
    }

    /**
     * Creates a new ShipClass entity.
     *
     * @Route("/", name="classes_create")
     * @Method("POST")
     * @Template("DeepSpaceOneGameBundle:ShipClass:new.html.twig")
     */
    public function createAction(Request $request)
    {
        // TASK 2: create form and handle the request

        // TASK 2: update if condition
        if (false) {
            // TASK 2: create class

            $em = $this->getDoctrine()->getManager();
            // TASK 2: persist class
            $em->flush();

            return $this->redirect($this->generateUrl('classes'));
        }

        return array(
            // TASK 2: pass form to view
        );
    }

    /**
     * Displays a form to edit an existing ShipClass entity.
     *
     * @Route("/{id}/edit", name="classes_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction(ShipClass $class)
    {
        $deleteForm = $this->createDeleteForm($class);

        // TASK 2: create edit form for $class

        return array(
            'class' => $class,
            'delete_form' => $deleteForm->createView(),
            // TASK 2: pass form to view
        );
    }

    /**
     * Edits an existing ShipClass entity.
     *
     * @Route("/{id}", name="classes_update")
     * @Method("PUT")
     * @Template("DeepSpaceOneGameBundle:ShipClass:edit.html.twig")
     */
    public function updateAction(Request $request, ShipClass $class)
    {
        $deleteForm = $this->createDeleteForm($class);

        // TASK 2: create edit form and handle the request

        // TASK 2: update if condition
        if (false) {
            // TASK 2: update $class entity

            $em = $this->getDoctrine()->getManager();
            $em->flush();

            return $this->redirect($this->generateUrl('classes'));
        }

        return array(
            'class' => $class,
            'delete_form' => $deleteForm->createView(),
            // TASK 2: pass form to view
        );
    }

    /**
     * Finds and displays a ShipClass entity.
     *
     * @Route("/{id}", name="classes_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction(ShipClass $class)
    {
        $deleteForm = $this->createDeleteForm($class);

        return array(
            'class' => $class,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Deletes a ShipClass entity.
     *
     * @Route("/{id}", name="classes_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, ShipClass $class)
    {
        $form = $this->createDeleteForm($class);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($class);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('classes'));
    }

    /**
     * Creates a form to delete a ShipClass entity by id.
     *
     * @param ShipClass $class The ship class
     *
     * @return \Symfony\Component\Form\FormInterface The form
     */
    private function createDeleteForm(ShipClass $class)
    {
        return $this->createFormBuilder(null, array('style' => 'none'))
            ->setAction($this->generateUrl('classes_delete', array('id' => $class->getId())))
            ->setMethod('DELETE')
            ->add('delete', 'submit', array('attr' => array('class' => 'btn-danger')))
            ->getForm()
        ;
    }
}

src/DeepSpaceOne/GameBundle/Resources/views/ShipClass/edit.html.twig
{% extends '::base.html.twig' %}

{% set active_section = 'classes' %}

{% block body -%}
    <div class="page-header">
        <h1>Edit Ship Class</h1>
    </div>

    {# TASK 2: render form #}

    <ul class="record_actions list-inline">
        <li><a href="{{ path('classes') }}" class="btn btn-default"><span class="glyphicon glyphicon-list"></span> Back to the list</a></li>
        <li>{{ form(delete_form) }}</li>
    </ul>
{% endblock %}

src/DeepSpaceOne/GameBundle/Resources/views/ShipClass/index.html.twig
{% extends '::base.html.twig' %}

{% set active_section = 'classes' %}

{% block body -%}
    <div class="page-header">
        <h1>Ship Classes</h1>
    </div>

    <table class="records_list table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Crew</th>
                <th>Equipment</th>
                <th>Payload</th>
            </tr>
        </thead>
        <tbody>
        {% for class in classes %}
            <tr>
                <td><a href="{{ path('classes_edit', { 'id': class.id }) }}">{{ class.name }}</a></td>
                <td>{{ class.price }} credits</td>
                <td>{{ class.crewSize }}</td>
                <td>{{ class.equipmentCapacity }} mount points</td>
                <td>{{ class.payloadCapacity }} tons</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <ul class="list-inline">
        <li><a href="{{ path('classes_new') }}" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Add ship class</a></li>
    </ul>
{% endblock %}

src/DeepSpaceOne/GameBundle/Resources/views/ShipClass/new.html.twig
{% extends '::base.html.twig' %}

{% set active_section = 'classes' %}

{% block body -%}
    <div class="page-header">
        <h1>New Ship Class</h1>
    </div>

    {# TASK 2: render form #}

    <ul class="record_actions list-inline">
        <li><a href="{{ path('classes') }}" class="btn btn-default"><span class="glyphicon glyphicon-list"></span> Back to the list</a></li>
    </ul>
{% endblock %}

src/DeepSpaceOne/GameBundle/Resources/views/ShipClass/show.html.twig
{% extends '::base.html.twig' %}

{% set active_section = 'classes' %}

{% block body -%}
    <div class="page-header">
        <h1>Ship Class</h1>
    </div>

    <table class="record_properties table table-bordered">
        <tbody>
            <tr>
                <th class="span2">Name</th>
                <td>{{ class.name }}</td>
            </tr>
            <tr>
                <th>Crew</th>
                <td>{{ class.crewSize }}</td>
            </tr>
            <tr>
                <th>Equipment</th>
                <td>{{ class.equipmentCapacity }} mount points</td>
            </tr>
            <tr>
                <th>Payload</th>
                <td>{{ class.payloadCapacity }} tons</td>
            </tr>
        </tbody>
    </table>

    <ul class="record_actions list-inline">
        <li><a href="{{ path('classes') }}" class="btn btn-default"><span class="glyphicon glyphicon-list"></span> Back to the list</a></li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}